### ISSUE TITLE
HTTP/2.0 500  error

### ISSUE THREAD

**Issue by rosche98** [devinsays/woocommerce-coupon-restrictions#15]
I tired to use the woo commerce coupon restriction plugin, but once I try to press place order, it does not place the order and gives this following error 

HTTP/2.0 500 

![screen shot 2018-04-16 at 4 09 12 pm](https://user-images.githubusercontent.com/38430711/38815414-29d270ce-4194-11e8-9274-30e2def9bed5.png)

this error message is written below "click here to enter your code", and no order is placed. 
when using other coupons, which does not have the restrictions, or make orders with no coupons at all, everything works fine.
Any help will be very much appreciated. 

wordpress: Version 4.9.5
WooCommerce: Version 3.3.5
Theme used: Flatsome Version 3.5.2

**Comment by devinsays** [comment]
Is there a js error in the console? Can you paste the results here?

**Comment by devinsays** [comment]
Fixes in 5b1ba935a3a45a7aa6a09448ebac1eabbde9d701.
