### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by abclution** [devinsays/woocommerce-coupon-restrictions#16]
Hi there Devin, cool plugin, but for some reason I can't get parts of it to work. 
Plugin activated.
Coupon created with "Free Shipping"
New Users Only
Coupon Applies successfully on the order.

On checkout I get Internal Server Error.

I am trying to validate the coupon for "New Customers Only" getting this error.

`[Sun Apr 29 12:51:37.584383 2018] [fcgid:warn] [pid 28257] [client 62.38.149.238:62397] mod_fcgid: stderr: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Coupon_Restrictions_Validation::check_new_customer_coupon_checkout(), 0 passed in /home/dev_/www/wp-content/plugins/woocommerce-coupon-restrictions/includes/class-wc-coupon-restrictions-validation.php on line 290 and exactly 2 expected in /home/dev_/www/wp-content/plugins/woocommerce-coupon-restrictions/includes/class-wc-coupon-restrictions-validation.php:328, referer: https://dev.shoptest.eu/en/checkout/
[Sun Apr 29 12:51:37.584392 2018] [fcgid:warn] [pid 28257] [client 62.38.149.238:62397] mod_fcgid: stderr: Stack trace:, referer: https://dev.shoptest.eu/en/checkout/
[Sun Apr 29 12:51:37.584400 2018] [fcgid:warn] [pid 28257] [client 62.38.149.238:62397] mod_fcgid: stderr: #0 /home/dev_/www/wp-content/plugins/woocommerce-coupon-restrictions/includes/class-wc-coupon-restrictions-validation.php(290): WC_Coupon_Restrictions_Validation::check_new_customer_coupon_checkout(), referer: https://dev.shoptest.eu/en/checkout/
[Sun Apr 29 12:51:37.584408 2018] [fcgid:warn] [pid 28257] [client 62.38.149.238:62397] mod_fcgid: stderr: #1 /home/dev_/www/wp-includes/class-wp-hook.php(288): WC_Coupon_Restrictions_Validation::validate_coupons_at_checkout(Array), referer: https://dev.shoptest.eu/en/checkout/
[Sun Apr 29 12:51:37.584416 2018] [fcgid:warn] [pid 28257] [client 62.38.149.238:62397] mod_fcgid: stderr: #2 /home/dev_/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array), referer: https://dev.shoptest.eu/en/checkout/
[Sun Apr 29 12:51:37.584424 2018] [fcgid:warn] [pid 28257] [client 62.38.149.238:62397] mod_fcgid: stderr: #3 /home/dev_/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array), referer: https://dev.shoptest.eu/en/checkout/
[Sun Apr 29 12:51:37.584432 2018] [fcgid:warn] [pid 28257] [client 62.38.149.238:62397] mod_fcgid: stderr: #4 /home/de in /home/dev_/www/wp-content/plugins/woocommerce-coupon-restrictions/includes/class-wc-coupon-restrictions-validation.php on line 328, referer: https://dev.shoptest.eu`

**Comment by abclution** [comment]
So, I'm not a programmer but I can figure stuff out sometimes.

includes/class-wc-coupon-restrictions-validation.php  Line 290ish

**Obviously the log is crying about not being passed parameters, I changed this area:** 
Line 290
                                   // Check if coupon is restricted to new customers.
                                        if ( 'new' == $customer_restriction_type ) {
                                                $valid = self::check_new_customer_coupon_checkout(  );
                                        }

                                        // Check if coupon is restricted to existing customers.
                                        if ( 'existing' == $existing_customers_restriction ) {
                                                $valid = self::check_existing_customer_coupon_checkout();
                                        }

to 

                                          // Check if coupon is restricted to new customers.
                                        if ( 'new' == $customer_restriction_type ) {
                                                $valid = self::check_new_customer_coupon_checkout( $coupon, $code );
                                        }

                                        // Check if coupon is restricted to existing customers.
                                        if ( 'existing' == $existing_customers_restriction ) {
                                                $valid = self::check_existing_customer_coupon_checkout();
                                        }



It appears that its failing just cause the  $coupon, $code are expected by the 
check_new_customer_coupon_checkout function. 

From what I can understand this same issue should appear on the existing customer section as well. I will tes.

**Comment by abclution** [comment]
Ok this behaviour does not occur  on a coupon for an existing customer. I dont know why and I don't know the repercussions of the changes I have made.

**Comment by devinsays** [comment]
Hey @abclution. Thanks for the bug report and log information. There was indeed an issue here (actually a couple). I've just updated the version to 1.5.0 with all the fixes. Let me know how it works for you now.

**Comment by abclution** [comment]
Cool thanks, will do.
