### ISSUE TITLE
Github Updater Lite Integration - Native plugin updates from Github

### ISSUE THREAD

**Issue by abclution** [devinsays/woocommerce-coupon-restrictions#17]
Would like to propose integrating Github Updater Lite into this plugin.
Extremely easy integration, and will give native in-wordpress updates to the plugin whenever you make a new build. 

I can fork, put the integrations and then submit a pull request if you would like.
Its literally 3-4 lines. :)

https://github.com/FacetWP/github-updater-lite

**Comment by devinsays** [comment]
Hi @abclution. I made some comments on your pull request.

However, I totally understand the need for automatic updates. I'll likely be including a mechanism for this in the next couple months.
