### ISSUE TITLE
Checkout Failure: Logged Out Returning Customer with New Customer Restriction

### ISSUE THREAD

**Issue by devinsays** [devinsays/woocommerce-coupon-restrictions#3]
If a logged out user tries to checkout with an email address that has placed an order before, it causes an "Unable to fix malformed JSON" error. It looks like the coupon notice is being displayed for some reason.

```{"result":"failure","messages":"
\n\t\t\t
Coupon removed. Code \"basic\" is only valid for new customers.<\/li>\n\t\t\t<\/li>\n\t<\/ul>\n","refresh":true,"reload":false}```

**Comment by lordspace** [comment]
I have checked your upwork project (upwork.com/jobs/~011007a07de4ff324a). I think this has to do with some notices php outputs. 
You can keep the debugging ON but not display it but log it and later inspect it.
