### ISSUE TITLE
[review] Constants

### ISSUE THREAD

**Issue by javorszky** [devinsays/woocommerce-coupon-restrictions#30]
This is a personal preference, but makes life easier when dealing with reusable bits like plugin URL / paths.

Currently

```php
// you have to call this every time you want to use $path
$path = WC_Coupon_Restrictions::plugin_path();

wp_register_script( 'something', $path . '/assets/something.js', ...);
```

Instead in the main plugin file do

```php
define( 'WCCR_PATH', untrailingslashit( plugin_dir_path( __FILE__ ) );
```
And then later you don't need to call a method:

```php
wp_register_script( 'something', WCCR_PATH . '/assets/something.js', ...);
```

**Comment by devinsays** [comment]
It's definitely less verbose to use a constant, but I'm going to keep as is. It's only used a few times in the main class and I like that it's scoped (even though chance of some other plugin defining that constant is low).
