### ISSUE TITLE
[review] Can woocommerce-coupon-restrictions option be a string?

### ISSUE THREAD

**Issue by javorszky** [devinsays/woocommerce-coupon-restrictions#33]
You're storing an array as the value of the `woocommerce-coupon-restrictions` option:

```php
update_option( 'woocommerce-coupon-restrictions', array( 'version' => $this->version ) );
```

There is no other data being put into that option. Because of that, would it be easier to use a simple string as the option value like so? 

```php
update_option( 'woocommerce-coupon-restrictions-version', $this->version );
```

Slight adjustment to code is needed on all other places where you're using this. The upside is that when you look at the database, you'd see `1.6.0` instead of `a:1;{s:5;"1.6.0"}`. The first one is a lot easier to deal with.

You'd also save a function call from `maybe_unserialize`.

**Comment by devinsays** [comment]
This is mostly future proofing. If I add additional settings in the future, most likely I'd like to store them all within one option.
