### ISSUE TITLE
[review] Use coupon object instead of global $post

### ISSUE THREAD

**Issue by javorszky** [devinsays/woocommerce-coupon-restrictions#36]
WooCommerce [passes both the coupon's ID and the coupon object](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php#L280) to the action hook.

Your plugin should use those instead of the `global $post`. Currently it will accidentally work, as long as no site will use a custom data store to store coupons in and move them out of the posts table.

Because of that `get_post_meta` and the other functions are discouraged, and you should use `$coupon->set_meta_data()` etc instead. Do not forget to call `$coupon->save()` at the end.

**Comment by javorszky** [comment]
See also `update_post_meta` on the coupon restriction option save.

**Comment by devinsays** [comment]
Fixed. Thanks for pointing this out!
