### ISSUE TITLE
[review] Consistency in constructing html

### ISSUE THREAD

**Issue by javorszky** [devinsays/woocommerce-coupon-restrictions#37]
In the `location_restriction` method, you have a mix of `echo` and stepping out of php-land to write literal html [here](https://github.com/devinsays/woocommerce-coupon-restrictions/blob/master/includes/class-wc-coupon-restrictions-admin.php#L87-L91).

I generally find it's best to keep things consistent. Either step out of php for all html strings, or stay within php-land and `echo` them.

**Comment by devinsays** [comment]
Resolved in https://github.com/devinsays/woocommerce-coupon-restrictions/pull/66.
