### ISSUE TITLE
[review] Use curly brace blocks instead of colon / endif / endforeach statements

### ISSUE THREAD

**Issue by javorszky** [devinsays/woocommerce-coupon-restrictions#44]
Stylistic choice. Consistency. Code folding. Code style.

The WP Coding standards are totally okay with the following syntax:

```
if ( condition ) : 
    // things
endif;
```
I still find it easier to work with if I know everything is curly braced.

**Comment by devinsays** [comment]
Resolved in https://github.com/devinsays/woocommerce-coupon-restrictions/pull/80.
