### ISSUE TITLE
[review] Performance hazard - get orders by customer

### ISSUE THREAD

**Issue by javorszky** [devinsays/woocommerce-coupon-restrictions#51]
```
// If there isn't a user account, we can check against orders.
$customer_orders = wc_get_orders( array(
	'status' => array( 'wc-processing', 'wc-completed' ),
	'email'  => $email,
	'limit'  => 1
) );
```
https://github.com/devinsays/woocommerce-coupon-restrictions/blob/master/includes/class-wc-coupon-restrictions-validation.php#L554-L559

If the orders are still stored in the posts table, this will query the postmeta table and checking against meta_value, which is not indexed.

Additionally, the `wc_get_orders` function, while it does offer the `email` arg for whatever reason, does NOT use it for anything.

In my testing, I had this code

```php
add_action( 'wp_loaded', function() {
	$orders = wc_get_orders( array(
		'status' => array( 'wc-processing', 'wc-completed' ),
		'email'  => 'william@example.org', // I do not have an order with this email address anywhere
		'limit'  => 1
	) );

	dd($orders);
} );
```

This returned me one order for myself. Digging more into that, the request run against the database was this:

```sql
SELECT   wp_posts.ID
FROM wp_posts 
WHERE 1=1 
AND wp_posts.post_type IN ('shop_order', 'shop_order_refund')
AND ((
	wp_posts.post_status = 'wc-processing'
	OR wp_posts.post_status = 'wc-completed'
))
ORDER BY wp_posts.post_date DESC LIMIT 0, 1
```

The email wasn't used anywhere.

This needs reworking, because currently it will lead to bad data.

**Comment by devinsays** [comment]
The function is working correctly. When I looked through the queries, I'm pretty sure this is what is being run:

```
SELECT wp_posts.ID
FROM wp_posts 
INNER JOIN wp_postmeta
ON ( wp_posts.ID = wp_postmeta.post_id )
WHERE 1=1 
AND ( ( wp_postmeta.meta_key = '_billing_email'
AND wp_postmeta.meta_value = 'email@example.com' ) )
AND wp_posts.post_type IN ('shop_order', 'shop_order_refund')
AND ((wp_posts.post_status = 'wc-processing'
OR wp_posts.post_status = 'wc-completed'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_date DESC
LIMIT 0, 1
```

It looks like "email" is a legacy parameter, and should be updated to billing_email: https://github.com/woocommerce/woocommerce/blob/46df086e58a0a152988c85da20a348251fd8a7e7/includes/wc-order-functions.php#L33

I agree performance could be an issue on a site with a huge number of orders. I think my recommendation for large sites would be to create a customer account in the background if a new customer makes a purchase, and then this secondary check would never be needed (it would just query against the user table). However, I'd need to provide a way to opt-out of that final validation check.

Do you have any other thoughts or suggestions for how to do it in a performant way?

**Comment by javorszky** [comment]
Hm, not really. The best way to do this query is finding a way to not do it.

There are five ways to go about this:

* use a custom data store for the orders. This is coming in WC core at some point in time. The downside is that you'd have to support it for now, and if data corruption happens, that's inconvenient, plus 3rd party plugin compatibility is iffy
* use WPEngine's customer order index plugin that should keep things in sync. It just works. The downside is that the publicly available version is old (https://github.com/pmgarman/wc-customer-order-index). I'm trying to find a fresher version
* use cache to store the result of this query
* use `WC_Customer::is_paying_customer` instead to determine whether coupon should be applied
* use `wc_get_customer_last_order( $user_id )` to determine if there is a last order or not

I recommend one of the last two.

**Comment by devinsays** [comment]
New setting has been added. Query now runs against user accounts only by default.

If site owner wants to query against orders as well, they still have the option, but they need to opt-in. Still working on additional documentation and notices so that they are aware of the performance impact.

fd5c6751374cc618c99984bcd2d5a8074cb70fce
