### ISSUE TITLE
syntax error , line 424

### ISSUE THREAD

**Issue by yonglinteh** [devinsays/woocommerce-coupon-restrictions#6]
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /home4/waealy0acpcs/public_html/wp-content/plugins/woocommerce-coupon-restrictions-master/woocommerce-coupon-restrictions.php on line 424

**Comment by jatiyanon** [comment]
Duplicate of #5

**Comment by devinsays** [comment]
Thanks for the bug report (for some reason email notifications weren't coming through to me). Try it now, there have been some changes in the last week.
